version: '3'
services:
  geokit:
    image: developmentseed/geokit:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app/data
    env_file:
      - ./env.sample