version: 2
jobs:
  geokit:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - caches/geokit.tar

      - run:
          name: Load docker image cache
          command: |
            docker load -i caches/geokit.tar || true

      - run:
          name: Build application docker image
          command: |
            docker build --cache-from=geokit -t geokit geokit/

      - run:
          name: Save docker image cache
          command: |
            mkdir -p caches
            docker save -o caches/geokit.tar geokit

      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - caches/geokit.tar

      - deploy:
          name: Push docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
              VERSION=$(grep -m1 version package.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')
            else
              VERSION="$(echo $CIRCLE_BRANCH | sed 's/\//\-/g')-$(echo $CIRCLE_SHA1 | cut -c -7)"
            fi
            docker tag geokit developmentseed/geokit:${VERSION}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push developmentseed/geokit:${VERSION}

workflows:
  version: 2
  build_and_push:
    jobs:
      - geokit
