version: 2
jobs:
  geokit:
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      - PRODUCTION_BRANCH: develop
    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - caches/geokit.tar

      - run:
          name: Load docker image cache
          command: |
            docker load -i caches/geokit.tar || true

      - run:
          name: Build application docker image
          command: |
            docker build --cache-from=geokit -t geokit .

      - run:
          name: Save docker image cache
          command: |
            mkdir -p caches
            docker save -o caches/geokit.tar geokit

      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - caches/geokit.tar
      - deploy:
          name: Push api Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "${PRODUCTION_BRANCH}" ]; then
              VERSION=latest
            else
              VERSION="${CIRCLE_BRANCH}"
            fi
            docker tag geokit developmentseed/geokit:${VERSION}
            docker login --username $DOCKER_USER --password $DOCKER_TOKEN
            docker push developmentseed/geokit:${VERSION}

workflows:
  version: 2
  build_and_push:
    jobs:
      - geokit
